/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct operands {
	double left;
	double right;
	char operatorType;
};
typedef struct operands operands;
#ifdef __cplusplus
extern "C" bool_t xdr_operands(XDR *, operands*);
#elif __STDC__
extern  bool_t xdr_operands(XDR *, operands*);
#else /* Old Style C */
bool_t xdr_operands();
#endif /* Old Style C */


#ifdef __cplusplus
extern "C" bool_t xdr_operands(XDR *, operands*);
#elif __STDC__
extern  bool_t xdr_operands(XDR *, operands*);
#else /* Old Style C */
bool_t xdr_operands();
#endif /* Old Style C */


#define CALCULATOR_PROG ((rpc_uint)12344321)
#define CALCULATOR_VARS ((rpc_uint)1)

#ifdef __cplusplus
#define DIV ((rpc_uint)1)
extern "C" double * div_1(operands *, CLIENT *);
extern "C" double * div_1_svc(operands *, struct svc_req *);
#define PM ((rpc_uint)2)
extern "C" double * pm_1(double *, CLIENT *);
extern "C" double * pm_1_svc(double *, struct svc_req *);
#define PROC ((rpc_uint)3)
extern "C" double * proc_1(double *, CLIENT *);
extern "C" double * proc_1_svc(double *, struct svc_req *);
#define ONETOX ((rpc_uint)4)
extern "C" double * onetox_1(double *, CLIENT *);
extern "C" double * onetox_1_svc(double *, struct svc_req *);
#define COSINUS ((rpc_uint)5)
extern "C" double * cosinus_1(double *, CLIENT *);
extern "C" double * cosinus_1_svc(double *, struct svc_req *);
#define SINUS ((rpc_uint)6)
extern "C" double * sinus_1(double *, CLIENT *);
extern "C" double * sinus_1_svc(double *, struct svc_req *);
#define MYSQRT ((rpc_uint)7)
extern "C" double * mysqrt_1(double *, CLIENT *);
extern "C" double * mysqrt_1_svc(double *, struct svc_req *);
#define MYLN ((rpc_uint)8)
extern "C" double * myln_1(double *, CLIENT *);
extern "C" double * myln_1_svc(double *, struct svc_req *);
#define MYEXP ((rpc_uint)9)
extern "C" double * myexp_1(double *, CLIENT *);
extern "C" double * myexp_1_svc(double *, struct svc_req *);
#define MUL ((rpc_uint)10)
extern "C" double * mul_1(operands *, CLIENT *);
extern "C" double * mul_1_svc(operands *, struct svc_req *);
#define SUB ((rpc_uint)11)
extern "C" double * sub_1(operands *, CLIENT *);
extern "C" double * sub_1_svc(operands *, struct svc_req *);
#define ADD ((rpc_uint)12)
extern "C" double * add_1(operands *, CLIENT *);
extern "C" double * add_1_svc(operands *, struct svc_req *);
#define EQU ((rpc_uint)13)
extern "C" double * equ_1(operands *, CLIENT *);
extern "C" double * equ_1_svc(operands *, struct svc_req *);

#elif __STDC__
#define DIV ((rpc_uint)1)
extern  double * div_1(operands *, CLIENT *);
extern  double * div_1_svc(operands *, struct svc_req *);
#define PM ((rpc_uint)2)
extern  double * pm_1(double *, CLIENT *);
extern  double * pm_1_svc(double *, struct svc_req *);
#define PROC ((rpc_uint)3)
extern  double * proc_1(double *, CLIENT *);
extern  double * proc_1_svc(double *, struct svc_req *);
#define ONETOX ((rpc_uint)4)
extern  double * onetox_1(double *, CLIENT *);
extern  double * onetox_1_svc(double *, struct svc_req *);
#define COSINUS ((rpc_uint)5)
extern  double * cosinus_1(double *, CLIENT *);
extern  double * cosinus_1_svc(double *, struct svc_req *);
#define SINUS ((rpc_uint)6)
extern  double * sinus_1(double *, CLIENT *);
extern  double * sinus_1_svc(double *, struct svc_req *);
#define MYSQRT ((rpc_uint)7)
extern  double * mysqrt_1(double *, CLIENT *);
extern  double * mysqrt_1_svc(double *, struct svc_req *);
#define MYLN ((rpc_uint)8)
extern  double * myln_1(double *, CLIENT *);
extern  double * myln_1_svc(double *, struct svc_req *);
#define MYEXP ((rpc_uint)9)
extern  double * myexp_1(double *, CLIENT *);
extern  double * myexp_1_svc(double *, struct svc_req *);
#define MUL ((rpc_uint)10)
extern  double * mul_1(operands *, CLIENT *);
extern  double * mul_1_svc(operands *, struct svc_req *);
#define SUB ((rpc_uint)11)
extern  double * sub_1(operands *, CLIENT *);
extern  double * sub_1_svc(operands *, struct svc_req *);
#define ADD ((rpc_uint)12)
extern  double * add_1(operands *, CLIENT *);
extern  double * add_1_svc(operands *, struct svc_req *);
#define EQU ((rpc_uint)13)
extern  double * equ_1(operands *, CLIENT *);
extern  double * equ_1_svc(operands *, struct svc_req *);

#else /* Old Style C */
#define DIV ((rpc_uint)1)
extern  double * div_1();
extern  double * div_1_svc();
#define PM ((rpc_uint)2)
extern  double * pm_1();
extern  double * pm_1_svc();
#define PROC ((rpc_uint)3)
extern  double * proc_1();
extern  double * proc_1_svc();
#define ONETOX ((rpc_uint)4)
extern  double * onetox_1();
extern  double * onetox_1_svc();
#define COSINUS ((rpc_uint)5)
extern  double * cosinus_1();
extern  double * cosinus_1_svc();
#define SINUS ((rpc_uint)6)
extern  double * sinus_1();
extern  double * sinus_1_svc();
#define MYSQRT ((rpc_uint)7)
extern  double * mysqrt_1();
extern  double * mysqrt_1_svc();
#define MYLN ((rpc_uint)8)
extern  double * myln_1();
extern  double * myln_1_svc();
#define MYEXP ((rpc_uint)9)
extern  double * myexp_1();
extern  double * myexp_1_svc();
#define MUL ((rpc_uint)10)
extern  double * mul_1();
extern  double * mul_1_svc();
#define SUB ((rpc_uint)11)
extern  double * sub_1();
extern  double * sub_1_svc();
#define ADD ((rpc_uint)12)
extern  double * add_1();
extern  double * add_1_svc();
#define EQU ((rpc_uint)13)
extern  double * equ_1();
extern  double * equ_1_svc();
#endif /* Old Style C */

#endif /* !_CALC_H_RPCGEN */
