/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Calc.h"

bool_t
xdr_operands(xdrs, objp)
	XDR *xdrs;
	operands *objp;
{

	if (!xdr_double(xdrs, &objp->left))
		return (FALSE);
	if (!xdr_double(xdrs, &objp->right))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->operatorType))
		return (FALSE);
	return (TRUE);
}
